name: Subir Front

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Salva apenas o conteúdo do dist/controle-pcp/browser
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: lojagi
          path: dist/controle-pcp/browser/*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Baixa o conteúdo direto na pasta ./build
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: lojagi
          path: build

      - name: Show files (debug)
        run: ls -R build

      # (Opcional) limpa o diretório remoto antes do deploy
      - name: Limpar diretório remoto
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            rm -rf /var/www/controlepcp.kgsistemas.com.br/public_html/*
            mkdir -p /var/www/controlepcp.kgsistemas.com.br/public_html

      # Copia apenas o conteúdo do build para a pasta pública
      - name: Copiar arquivos via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "*"
          target: "/var/www/controlepcp.kgsistemas.com.br/public_html"
          recursive: true
