name: Subir Front

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Salva apenas o conteúdo do dist/controle-pcp/browser
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: controlepcp
          path: dist/controle-pcp/browser/*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: controlepcp
          path: public_html

      - name: Show files (debug)
        run: ls -R public_html

      - name: Limpar diretório remoto
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            find /var/www/controlepcp.kgsistemas.com.br/public_html -type f -delete

      - name: Copiar arquivos via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "public_html/*"
          target: "/var/www/controlepcp.kgsistemas.com.br"
          recursive: true
